# Generated by Django 5.0 on 2025-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_projectdetail_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='image', null=True, upload_to='', verbose_name='image')),
                ('description', models.TextField(blank=True, null=True)),
                ('project_completed', models.PositiveIntegerField(blank=True, null=True, verbose_name='project completed')),
                ('awards', models.PositiveIntegerField(blank=True, null=True, verbose_name='awards completed')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='years experience')),
                ('satisfaction', models.PositiveIntegerField(blank=True, null=True, verbose_name='satisfaction percent')),
            ],
        ),
    ]
