# Generated by Django 5.0 on 2025-08-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ourservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='my address'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='myemail',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='my phone'),
        ),
    ]
