# Generated by Django 5.0 on 2025-08-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutme_address_aboutme_myemail_aboutme_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'AboutMe', 'verbose_name_plural': 'AboutMe'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='gallerychild',
            options={'verbose_name': 'GalleryChild', 'verbose_name_plural': 'GalleryChild'},
        ),
        migrations.AlterModelOptions(
            name='ourservice',
            options={'verbose_name': 'OurService', 'verbose_name_plural': 'OurService'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'project'},
        ),
        migrations.AlterModelOptions(
            name='projectchild',
            options={'verbose_name': 'ProjectChild', 'verbose_name_plural': 'ProjectChild'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'silder', 'verbose_name_plural': 'silder'},
        ),
    ]
