# Generated by Django 5.0 on 2025-09-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_aboutme_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='area',
            new_name='scale',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='location',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='year',
            new_name='type',
        ),
    ]
